### ISSUE TITLE
API feedback

### ISSUE THREAD

**Issue by max-mapper** [maxogden/electron-microscope#1]
[this](https://github.com/maxogden/electron-microscope#electron-microscope) is a new module i'm working on that wraps electron in an API suitable for scraping, automation etc.

I'm interested in getting early feedback on the JS API + semantics I have so far:
- https://github.com/maxogden/electron-microscope#usage
- JS API: https://github.com/maxogden/electron-microscope/blob/master/hoyt.js (run with `electron hoyt.js`)
- CLI API: https://github.com/maxogden/electron-microscope/blob/master/test/test.js

I looked at phantom.js and casper.js for some inspiration, but I'd be open to other suggestions on APIs that get this kind of thing 'right'

edit: currently you have to `npm run bundle` before this will work

![24e1db6d66e00b90c99c68487e6b365c692b619cd3f2063b5a284b1182766b43](https://cloud.githubusercontent.com/assets/39759/8664019/7213697a-2986-11e5-958f-7f4a04c81af0.jpg)

**Comment by mafintosh** [comment]
a `scope.eval(script, cb)` function would be a nice shorthand to have as well

**Comment by AutomatedTester** [comment]
What does this library have over something like [WebDriver](https://github.com/seleniumhq/selenium)? [WebDriver](https://github.com/seleniumhq/selenium) already has stable API that is now being standardised with a [W3C Specification](http://w3c.github.io/webdriver/webdriver-spec.html) that is being implemented in Chrome, Firefox and Edge.

**Comment by max-mapper** [comment]
@AutomatedTester Browsing the [docs for WebDriver](http://seleniumhq.github.io/selenium/docs/api/javascript/class_webdriver_WebDriver.html) it looks like if we wanted to implement that API it would take quite a bit of work, since all the calls would have to be done with RPC and we would likely have to make major contributions to Electron to let us implement the WebDriver APIs. There are some cool ideas in there though, thanks for sharing.

**Comment by AutomatedTester** [comment]
@maxogden You wouldn't have to do any implementations since there are already a number that do that.

Since I am guessing you only care about JavaScript ones see the following list from a [npm search](https://www.npmjs.com/search?q=webdriver)
- [WebDriverIO](https://www.npmjs.com/package/webdriverio)
- [Selenium-WebDriver](https://www.npmjs.com/package/selenium-webdriver) Official bindings from the WebDriver OSS project
- [wd](https://www.npmjs.com/package/wd)

While I am all for people scratching their own itch I do wonder if colloborating with the other projects would help you reach your end goal quicker.

**Comment by max-mapper** [comment]
@AutomatedTester the WebDriver API seems pretty overengineered for the types of things I'm interested in personally, but in the future I'll consider it
